[workspace]
members = [
    "boot/uefi-loader",
    "shared/abi",
    "shared/serial",
    "tools/xtask",
    "kernel",
    "userland/init",
    "userland/shell",
    "userland/libnewos",
    "userland/fault-tester",
]
default-members = [
    "shared/abi",
    "tools/xtask",
]
exclude = [
    "kernel",
    "userland/init",
    "userland/shell",
    "userland/libnewos",
    "shared/abi",
    "shared/serial",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Uttam", "Codex", "Antigravity"]
repository = "https://github.com/uttampaliwal/NewOS"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
