[package]
name = "newos-kernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "newos-kernel-image"
path = "src/bin/newos-kernel-image.rs"
test = false
bench = false

[dependencies]
newos-abi = { path = "../shared/abi" }
